server:
  port: 1123

server1:
  ip: 47.112.207.98


spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://47.112.207.98:2181
  consumer:
    check: false
    timeout: 30000
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 47.112.207.98:22122
  # - 47.112.207.98:22122 可以多个,集群时
  connect-timeout: 600
  so-timeout: 1500




